### ISSUE TITLE
AEM upgrade from 6.2 to 6.5

### ISSUE THREAD

**Issue by vandsvna** [adobe/aem-project-archetype#391]
### Getting below error when i upload  a package in AEM 6.5
ERROR* [FelixDispatchQueue] IA_Wrapper_Services.core FrameworkEvent ERROR (org.osgi.framework.BundleException: Unable to resolve IA_Wrapper_Services.core [582](R 582.0): missing requirement [IA_Wrapper_Services.core [582](R 582.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0)) Unresolved requirements: [[IA_Wrapper_Services.core [582](R 582.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0))])
org.osgi.framework.BundleException: Unable to resolve IA_Wrapper_Services.core [582](R 582.0): missing requirement [IA_Wrapper_Services.core [582](R 582.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0)) Unresolved requirements: [[IA_Wrapper_Services.core [582](R 582.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0))]
at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
at java.lang.Thread.run(Unknown Source)

#### AEM 6.5

Logs - ERROR* [FelixDispatchQueue] IA_Wrapper_Services.core FrameworkEvent ERROR (org.osgi.framework.BundleException: Unable to resolve IA_Wrapper_Services.core [582](R 582.0): missing requirement [IA_Wrapper_Services.core [582](R 582.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0)) Unresolved requirements: [[IA_Wrapper_Services.core [582](R 582.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0))])
org.osgi.framework.BundleException: Unable to resolve IA_Wrapper_Services.core [582](R 582.0): missing requirement [IA_Wrapper_Services.core [582](R 582.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0)) Unresolved requirements: [[IA_Wrapper_Services.core [582](R 582.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.event.jobs)(version>=1.5.0)(version<=2.0.0))]
at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
at java.lang.Thread.run(Unknown Source)

**Comment by vandsvna** [comment]
Plz reply if some one has faced this issue, it's urgent
