### ISSUE TITLE
[Page] Error found in pages created of a CIF included  project

### ISSUE THREAD

**Issue by VarsTheMars** [adobe/aem-project-archetype#535]
The pages in a project created by including the CIF core components from the latest archetype have a Default Sling script error and are not authorable in the local instance.

The archetype command for the project creation:
``` 
mvn archetype:generate -DarchetypeGroupId=com.adobe.aem -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=24 -DappTitle="Archetype 24 Test Site CIF" -DappId="archetype24TestSiteCIF" -DgroupId="com.archetype24TestSiteCIF" -DartifactId="archetype-24-test-site-cif" -DincludeCommerce="y" 
```

The ERROR:
``` 
27.10.2020 18:33:39.126 *ERROR* [0:0:0:0:0:0:0:1 [1603803818998] GET /content/archetype24TestSiteCIF/us/en/home.html HTTP/1.1] com.day.cq.wcm.core.impl.WCMDeveloperModeFilter Error during include of SlingRequestPathInfo: path='/content/archetype24TestSiteCIF/us/en/home/jcr:content', selectorString='null', extension='html', suffix='null'
org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: Compilation errors in org/apache/sling/scripting/sightly/apps/core/cif/components/structure/page/v1/page/page__002e__html.java:
Line 46, column 2089 : com.adobe.cq.commerce.core.components.models.storeconfigexporter.StoreConfigExporter cannot be resolved to a type
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:510) [org.apache.sling.scripting.core:2.3.4]
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552) [org.apache.sling.engine:2.7.2]
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44) [org.apache.sling.engine:2.7.2]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:82) [org.apache.sling.engine:2.7.2]
	at com.day.cq.wcm.core.impl.WCMDeveloperModeFilter.doFilterWithErrorHandling(WCMDeveloperModeFilter.java:164) [com.day.cq.wcm.cq-wcm-core:5.13.152]
	at com.day.cq.wcm.core.impl.WCMDeveloperModeFilter.doFilter(WCMDeveloperModeFilter.java:135) [com.day.cq.wcm.cq-wcm-core:5.13.152]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:72) [org.apache.sling.engine:2.7.2]
	at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilter(WCMDebugFilter.java:138) [com.day.cq.wcm.cq-wcm-core:5.13.152]
.
.
.
.
.
[org.apache.felix.http.jetty:4.0.20]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [org.apache.felix.http.jetty:4.0.20]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [org.apache.felix.http.jetty:4.0.20]
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/core/cif/components/structure/page/v1/page/page__002e__html.java:
Line 46, column 2089 : com.adobe.cq.commerce.core.components.models.storeconfigexporter.StoreConfigExporter cannot be resolved to a type
	at org.apache.sling.scripting.sightly.impl.engine.compiled.SlingHTLMasterCompiler.compileSource(SlingHTLMasterCompiler.java:353) [org.apache.sling.scripting.sightly:1.4.4.140]
	at org.apache.sling.scripting.sightly.impl.engine.compiled.SlingHTLMasterCompiler.compileHTLScript(SlingHTLMasterCompiler.java:252) [org.apache.sling.scripting.sightly:1.4.4.140]
	at org.apache.sling.scripting.sightly.impl.engine.SightlyScriptEngine.compile(SightlyScriptEngine.java:66) [org.apache.sling.scripting.sightly:1.4.4.140]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:379) [org.apache.sling.scripting.core:2.3.4]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:184) [org.apache.sling.scripting.core:2.3.4]
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:491) [org.apache.sling.scripting.core:2.3.4]
	... 183 common frames omitted 

```

Here is snapshot of the page rendition:

![cif-page-error](https://user-images.githubusercontent.com/59619809/97305595-50c80400-1883-11eb-8b14-13239e8cff11.PNG)

**Comment by herzog31** [comment]
@VarsTheMars can you please specify your setup?

Since you didn't specify the AEM version when generating the project, the archetype will assume it's a project for AEMaaCS. So you should have the AEM SDK + CIF add-on installed.

**Comment by VarsTheMars** [comment]
@herzog31 The project is built from Archetype 24. I built the project for AEMaaCS only. I am having the SDK but I don't have the CIF add-ons installed. Can you send me the link to the CIF add-ons?

**Comment by herzog31** [comment]
@VarsTheMars You can find the CIF add-on in Software Distribution at experience.adobe.com.

**Comment by msagolj** [comment]
@VarsTheMars have the above comments answered your question and can the issue be closed ?

**Comment by VarsTheMars** [comment]
@msagolj Yes the issue has been clarified, it can be closed.

**Comment by msagolj** [comment]
@VarsTheMars thank you. closing
