### ISSUE TITLE
Replace and Update SASS build to use sass vs. node-sass

### ISSUE THREAD

**Issue by sachioross** [adobe/aem-project-archetype#586]
### Expected Behaviour
Running `npm runs start` starts a proxy and a browser window shows the proxied content from AEM with styles applied from local development. 

### Actual Behaviour
Compilation process fails due to unsupported OS

#### Steps to Reproduce
Run `npm run start` from ui.frontend module on Mac Big Sur using NodeJS 15.7

#### Platform and Version
Mac OS Big Sur
NodeJS 15.7

#### Sample Code that illustrates the problem
None: created project and attempt to build module

#### Logs taken while reproducing problem
```
▶ npm run start

> aem-maven-archetype@1.0.0 start
> webpack-dev-server --open --config ./webpack.dev.js

[HPM] Proxy created: [ '/content', '/etc.clientlibs' ]  ->  http://localhost:4502

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /projects/aem/febuild/ui.frontend
ℹ ｢wdm｣: wait until bundle finished: /
✖ ｢wdm｣: Hash: 2ecd5507acf4f7ba3a50
Version: webpack 4.44.2
Time: 2656ms
Built at: 01/27/2021 9:14:22 AM
Asset     Size  Chunks  Chunk Names
clientlib-site/site.js  885 KiB    site  site
Entrypoint site = clientlib-site/site.js

WARNING in ./src/main/webpack/site/main.ts
Module Warning (from (webpack)-import-glob-loader/index.js):
(Emitted value instead of an instance of Error) Empty results for "import "./**/*.js""
NonErrorEmittedError: (Emitted value instead of an instance of Error) Empty results for "import "./**/*.js""
at Object.emitWarning (/projects/aem/febuild/ui.frontend/node_modules/webpack/lib/NormalModule.js:160:16)
at replacer (/projects/aem/febuild/ui.frontend/node_modules/webpack-import-glob-loader/index.js:85:12)
at String.replace (<anonymous>)
at Object.module.exports (/projects/aem/febuild/ui.frontend/node_modules/webpack-import-glob-loader/index.js:91:20)

ERROR in ./src/main/webpack/site/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
at module.exports (/projects/aem/febuild/ui.frontend/node_modules/node-sass/lib/binding.js:13:13)
at Object.<anonymous> (/projects/aem/febuild/ui.frontend/node_modules/node-sass/lib/index.js:14:35)
at Module._compile (node:internal/modules/cjs/loader:1108:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
at Module.load (node:internal/modules/cjs/loader:973:32)
at Function.Module._load (node:internal/modules/cjs/loader:813:14)
at Module.require (node:internal/modules/cjs/loader:997:19)
at require (node:internal/modules/cjs/helpers:92:18)
at getDefaultSassImpl (/projects/aem/febuild/ui.frontend/node_modules/sass-loader/dist/index.js:198:10)
at Object.loader (/projects/aem/febuild/ui.frontend/node_modules/sass-loader/dist/index.js:80:29)
at /projects/aem/febuild/ui.frontend/node_modules/webpack/lib/NormalModule.js:316:20
at /projects/aem/febuild/ui.frontend/node_modules/loader-runner/lib/LoaderRunner.js:367:11
at /projects/aem/febuild/ui.frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:18
at runSyncOrAsync (/projects/aem/febuild/ui.frontend/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
at iterateNormalLoaders (/projects/aem/febuild/ui.frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
at iterateNormalLoaders (/projects/aem/febuild/ui.frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
at /projects/aem/febuild/ui.frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
at runSyncOrAsync (/projects/aem/febuild/ui.frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
at iterateNormalLoaders (/projects/aem/febuild/ui.frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
at Array.<anonymous> (/projects/aem/febuild/ui.frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
at Storage.finished (/projects/aem/febuild/ui.frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
at /projects/aem/febuild/ui.frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
at /projects/aem/febuild/ui.frontend/node_modules/graceful-fs/graceful-fs.js:123:16
at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3)
@ ./src/main/webpack/site/main.ts 1:0-21
ℹ ｢wdm｣: Failed to compile.
```

### Notes:
Researching this issue shows that node-sass and the corresponding LibSass is deprecated. The recommendation is to move to https://www.npmjs.com/package/sass

**Comment by kavinmehta-work** [comment]
+1
