### ISSUE TITLE
Missing CIF config dependency in archetype v.25

### ISSUE THREAD

**Issue by znikolovski** [adobe/aem-project-archetype#602]
### Expected Behaviour
Project generated with archetype successfully deploys and works in AEM Cloud Service

### Actual Behaviour
Project builds and deploys successfully but pages fail to open in AEM. 

### Reproduce Scenario (including but not limited to)
Generate a project with includeCommerce set to "y", deploy to AEM and open any page

#### Steps to Reproduce
1. Generate project from archetype - set includeCommerce to "y"
2. Run `mvn clean install -PautoInstallSinglePackage`
3. Navigate to site in AEM and select a page to edit

#### Platform and Version

Adobe Experience Manager 2021.1.4830.20210128T075814Z-201217
CIF Add-On 2021.02.01 

#### Logs taken while reproducing problem

Caused by: java.lang.NullPointerException: null
              at com.adobe.cq.commerce.core.components.internal.models.v1.storeconfigexporter.StoreConfigExporterImpl.initModel(StoreConfigExporterImpl.java:72) [com.adobe.commerce.cif.core-cif-components-core:1.7.0]
              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
              at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              at java.base/java.lang.reflect.Method.invoke(Method.java:566)
              at org.apache.sling.models.impl.ModelAdapterFactory.invokePostConstruct(ModelAdapterFactory.java:962) [org.apache.sling.models.impl:1.4.16]
              at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:761) [org.apache.sling.models.impl:1.4.16]
              ... 186 common frames omitted
11.02.2021 19:38:06.561 *INFO* [[0:0:0:0:0:0:0:1] [1613093886529] GET /libs/wcm/core/content/components.1613093603547.json HTTP/1.1] com.day.cq.wcm.core.impl.components.ComponentServlet provided components.

#### Resolution notes
We traced the issue to the fact that the following dependency was not included:
```
<dependency>
                <groupId>com.adobe.commerce.cif</groupId>
                <artifactId>core-cif-components-config</artifactId>
                <type>zip</type>
                <version>${core.cif.components.version}</version>
            </dependency>
```

Once this was added to the main pom.xml and the pom.xml in ui.apps and ui.all and embedded into the final package the error was resolved

**Comment by mhaack** [comment]
@znikolovski this was fixed by https://github.com/adobe/aem-project-archetype/pull/587 which will be part of the next release.
