### ISSUE TITLE
Archetype generation fails with maven-archetype-plugin 3.2.1

### ISSUE THREAD

**Issue by stefanseifert** [adobe/aem-project-archetype#857]
When creating a new AEM project without actually specifying an archetype *plugin* version on the command line, Maven uses the latest by default. And this is currently failing with the latest version 3.2.1 released a few days ago.

Exception:
```
[ERROR] groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-all is loaded in version 2.4.16 and you are trying to load version 2.4.8
[ERROR]         at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:529)
[ERROR]         at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:81)
[ERROR]         at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerExtensionModuleFromProperties(MetaClassRegistryImpl.java:174)
[ERROR]         at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$registerExtensionModuleFromProperties.call(Unknown Source)
[ERROR]         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
[ERROR]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
[ERROR]         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
[ERROR]         at groovy.grape.GrapeIvy.processCategoryMethods(GrapeIvy.groovy:290)
...
```

root cause is the change in the plugin dependencies for groovy in https://issues.apache.org/jira/browse/ARCHETYPE-565

**Comment by ziad-mesalmi** [comment]
@stefanseifert thanks, but which command should i do? to get download project without errors?

**Comment by ziad-mesalmi** [comment]
@stefanseifert 
With the release 33 we have already 2.4.8 groovy
https://github.com/adobe/aem-project-archetype/blob/release/33/src/main/resources/META-INF/archetype-post-generate.groovy

**Comment by stefanseifert** [comment]
workaround: until the PR #858 is merged and released specify the maven archetype plugin version on the command line to create a new AEM project.

example:
```
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=33 \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite"
```

**Comment by ziad-mesalmi** [comment]
@stefanseifert thanks a lot
