### ISSUE TITLE
xerces dependency seems to be old and causes errors

### ISSUE THREAD

**Issue by knennigtri** [adobe/aem-project-archetype#920]
### Expected Behaviour
When using AEM mocks, I should be able to load json into the AemContext without error.

### Actual Behaviour
When using AEM mocks, loading json files for testing content is failing with the error:
```
[INFO] Running com.adobe.training.core.models.StockplexSlingMockTest
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.119 s <<< FAILURE! - in com.adobe.training.core.models.StockplexSlingMockTest
[ERROR] testLoadedContent  Time elapsed: 0.013 s  <<< ERROR!
java.lang.IllegalStateException: Unable to enable secure processing.
        at com.adobe.training.core.models.StockplexSlingMockTest.setup(StockplexSlingMockTest.java:56)
Caused by: org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
        at com.adobe.training.core.models.StockplexSlingMockTest.setup(StockplexSlingMockTest.java:56)
...
[ERROR] Errors: 
[ERROR]   StockplexSlingMockTest.setup:56 » IllegalState Unable to enable secure process...
```
 The line the error refers to is:
``` java
context.load().json("/imported-stock-data.json","/my/folder");
```

### Reproduce Scenario (including but not limited to)
1. Create a project using the latest (36) archetype (AEM 6.5 or AEM SDK)
2. Create a json file at src/test/resources/my-test.json:
``` json
{ "myKey": "myVal" }
```
3. Update the HelloWorldModeTest.java setup() method at the bottom:
``` java
context.load().json("/my-test.json","/my/folder");
```
4. Run:
``` bash
cd core
mvn clean test
```

### Dependency that causes this
From what I can tell, there is a dependency that is adding this dependency to my project:
``` bash
<dependency>
        <groupId>xerces</groupId>
        <artifactId>xercesImpl</artifactId>
        <version>2.6.2</version>
        <scope>test</scope>
    </dependency>
```
If you manually add this dependency to your core/pom.xml and update it to the latest version, it successfully loads json content for my tests:
``` bash
<dependency>
        <groupId>xerces</groupId>
        <artifactId>xercesImpl</artifactId>
        <version>2.12.2</version>
        <scope>test</scope>
    </dependency>
```
I honestly have no idea if this is apart of the AEM archetype or an associated project, but this is an error when attempting to use AEM mocks from a project generated from Archetype 36.

**Comment by kenwoodward** [comment]
I am seeing the same issue.

I have project generated from Archetype 36 and I have to manually add the xerces dependency defined above to get around the error.  However, before adding the xerces dependency manually, I did not see version 2.6.2 being added.

Too add additional verification, I found this issue here as well: https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/junit-test-fails-with-saxnotrecognizedexception-while-loading/m-p/447252/highlight/true

Should the xerces dependency be added to core/pom.xml in the AEM Project Archetype?

**Comment by kenwoodward** [comment]
Did a bit more testing.  Confirmed that 2.6.2 does get loaded by default.  This is coming from the junit-addons dependency in the core pom.
```
        <dependency>
            <groupId>junit-addons</groupId>
            <artifactId>junit-addons</artifactId>
            <scope>test</scope>
        </dependency>
```
1.4 is the only version of junit-addons and it uses the old 2.6.2 version of xercesImpl.

**Comment by stefanseifert** [comment]
indeed, the dependency `junit-addons` is completely outdated, and should just be removed from the project, to avoid the injection of the also outdated xerces version into the test classpath.

i've created PR #1314 to remove it from the archetype itself.
