### ISSUE TITLE
react cloud project build error

### ISSUE THREAD

**Issue by rajeevyadav2** [adobe/aem-project-archetype#973]
Issue:
Created cloud react project using archetype 37.
On running the command mvn clean install -PautoInstallSinglePackage, frontend build fails with below error.
I am using mac.

[INFO] (node:23960) UnhandledPromiseRejectionWarning: TypeError: Network request failed
[INFO] (node:23960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[INFO] events.js:291
[INFO]       throw er; // Unhandled 'error' event
[INFO]       ^
[INFO] 
[INFO] Error: connect ECONNREFUSED 127.0.0.1:80
[INFO]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
[INFO] Emitted 'error' event on ClientRequest instance at:
[INFO]     at Socket.socketErrorListener (_http_client.js:427:9)
[INFO]     at Socket.emit (events.js:314:20)
[INFO]     at emitErrorNT (internal/streams/destroy.js:92:8)
[INFO]     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[INFO]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[INFO]   errno: 'ECONNREFUSED',
[INFO]   code: 'ECONNREFUSED',
[INFO]   syscall: 'connect',
[INFO]   address: '127.0.0.1',
[INFO]   port: 80
[INFO] }
[INFO] 

### Expected Behaviour
Build should be successful

### Actual Behaviour
ui.frontend build fails

### Reproduce Scenario (including but not limited to)
Create cloud react project using archetype 37.
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate -D archetypeGroupId=com.adobe.aem -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=37 -D appTitle="Demo" -D appId="demo" -D groupId="com.demo" -D aemVersion="cloud"  -D frontendModule="react"  -D singleCountry="n"

On running the command mvn clean install -PautoInstallSinglePackage, frontend build fails with below error.

#### Platform and Version
macbook

**Comment by kevinolivar** [comment]
Mhhhhh I am also on mac and running the above commands worked,

<img width="497" alt="Capture d’écran 2022-12-21 à 10 17 58" src="https://user-images.githubusercontent.com/81755864/208868865-3c450bc0-3fb8-4f31-bd5d-3ca6747f1dcd.png">


Maybe try again?

Platform and Version:
macOS Ventura 13.0

Npm 6.14.15
Node v14.18.2
java 11.0.13 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

Also,

`[INFO] Error: connect ECONNREFUSED 127.0.0.1:80`

Maybe something is still running? Or you haven't started your AEM instance?
